### ISSUE TITLE
getAsync() not available in 1.1 requirments set

### ISSUE THREAD

**Issue by mlafleur** [OfficeDev/Outlook-Add-in-ScanForMe#1]
The manifest defines a minimum mailbox version of v1.1 but the app makes a call to body.getAsync(). This method was not added to the body until v1.3. 

Either the minimum mailbox version should be moved to v1.3 or the availability of body.getAsync() should be checked at runtime. 

It should be noted that v1.3 is only supported by Outlook 2016 for Windows at this time so changing the minimum version will result in the add-in not loading on other Outlook editions. Given that this is sample code, it seems best to test for body.getAsync() at runtime. Otherwise the developer may be left wondering why the sample is failing to show up. I would also suggest firing an alert() if it isn't available greater clarity. 

Link to documentation on API sets: https://dev.outlook.com/reference/add-ins/tutorial-api-requirement-sets.html

**Comment by AndrewJByrne** [comment]
Hi Marc, 
Thanks for opening this issue. I like your approach and will merge the pull request as soon as possible.

Andrew
