### ISSUE TITLE
[Question] Add-in does not show in add-in bar

### ISSUE THREAD

**Issue by ndh103** [OfficeDev/Outlook-Add-in-ScanForMe#7]
![image](https://user-images.githubusercontent.com/752070/45026969-3e1e5f80-b06a-11e8-9ccd-5417cae5fb7a.png)

I've run the Scan For Me add-in but it does not show up in the add-in bar.

How can I make it show in add-in bar (like Report Phishing add-in in the image)

Thanks

**Comment by ElizabethSamuel-MSFT** [comment]
Hi @ndh103 , we no longer support custom panes (where you want the add-in displayed) in favor of add-in commands (where the add-in is actually displayed). For more details on supported extension points, please see the documentation (https://docs.microsoft.com/en-us/outlook/add-ins/#extension-points). There is also a blog that includes info about this deprecation: https://developer.microsoft.com/en-us/outlook/blogs/make-your-add-ins-available-in-the-office-ribbon/.

**Comment by ndh103** [comment]
Thanks @ElizabethSamuel-MSFT
